### ISSUE TITLE
[KB 4569] - SOF - small display changes

### ISSUE THREAD

**Issue by acrawford13** [acrawford13/booking-widget#115]
> **Auto-import from Kanbanise**
### Description
<ul><li>Move the&nbsp;<i>Is it possible to install the lock box?</i>&nbsp;in the&nbsp;<i>Getting in and out&nbsp;</i>section<br>&nbsp;</li><li><i>"we need 4 sets of keys" -&gt; </i>Change for <span style="background-color:rgb(248,248,248);color:rgb(29,28,29);"><i><strong>Pl</strong></i></span><i><strong>ease confirm with your account manager on the number of sets required </strong></i><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);"><i><strong>would be perfect</strong></i></span><br>&nbsp;</li><li><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);">Delete&nbsp;</span><i>are you providing an extra set of keys to guests</i><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);">&nbsp;field</span><br>&nbsp;</li><li>Remove <i>Classic rental price </i><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);">field from the form</span><br>&nbsp;</li><li><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);">Rephrase </span><i>closest metro/tube station for <strong>closest public transport station</strong></i><br>&nbsp;</li><li>Your listing - Add the BookingSync / Airbnb characters limitation for each fields (same of the ones in Rental form)&nbsp;<br>with warnings "Text cannot be longer than XXX characters" for each field.&nbsp;<br>- head<span style="color:hsl(0, 0%, 0%);">line for this description under 75 characters</span><br><span style="color:hsl(0, 0%, 0%);">- Summary - less than 150 characters&nbsp;</span><br><span style="color:hsl(0, 0%, 0%);">- </span><span style="background-color:rgb(255,255,255);color:hsl(0, 0%, 0%);">10000 characters in total for all the other fields combined&nbsp;</span><br>&nbsp;</li><li><span style="color:hsl(0, 0%, 0%);">Base price: Add in help text "((Property Manager)) management and channel fees are still to be deducted from the base price."</span><br>&nbsp;</li><li><span style="color:rgb(29,28,29);">Change the landing page once form is submitted by host for "The form has already been submitted to ((Property Manager)) and is currently being reviewed. Please reach out to your account manager should you have any question."</span><br>&nbsp;</li></ul><figure class="image"><img src="https://user-images.githubusercontent.com/18108338/96278322-42e5c980-0fcd-11eb-8f71-c41f409f6182.png"></figure>

### Subtasks
- [] <p>Move the&nbsp;<i>Is it possible to install the lock box?</i>&nbsp;in the&nbsp;<i>Getting in and out&nbsp;</i>section</p>
- [] <p><i>"we need 4 sets of keys" -&gt; </i>Change for <span style="color:rgb(29,28,29);"><i><strong>Pl</strong></i></span><i><strong>ease confirm with your account manager on the number of sets required</strong></i></p>
- [x] <p>Delete&nbsp;<i>are you providing an extra set of keys to guests</i>&nbsp;field</p>
- [x] <p>Remove <i>Classic rental price </i><span style="color:rgb(29,28,29);">field from the form</span></p>
- [x] <p><span style="color:rgb(29,28,29);">Rephrase </span><i>closest metro/tube station for <strong>closest public transport station</strong></i></p>
- [] <p>Add character limits</p>
- [x] <p><span style="color:hsl(0,0%,0%);">Base price: Add in help text "((Property Manager)) management and channel fees are still to be deducted from the base price."</span></p>
- [x] <p><span style="color:rgb(29,28,29);">Change the landing page once form is submitted by host for "The form has already been submitted to ((Property Manager)) and is currently being reviewed. Please reach out to your account manager should you have any question."</span></p>
### Discussion
> @alexandra-ja For the lockbox, I guess it&#039;s all good then there :D <span>@<strong id="k-mention">Andrea</strong></span> </p><p> 
> @alexandra-ja <strong>In order to operate smoothly, we need multiple sets of keys per property. Please confirm with your account manager the number of sets required. All sets of keys should be handed to your account manager before the first booking. In case you cannot provide us with the required number of sets, we will be able to assist in getting your keys replicated (with extra cost). </strong><br><br>-&gt; Yes that&#039;s perfect <span>@<strong id="k-mention">Andrea</strong></span> 
> @Andrea <i>"we need 4 sets of keys" -&gt; </i><span style="background-color:rgb(255,255,255);color:rgb(51,51,51);">Change for </span><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);"><i><strong>Pl</strong></i></span><i><strong>ease confirm with your account manager on the number of sets required </strong></i><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);"><i><strong>would be perfect</strong></i></span><br><br>This is the text at the moment:<br><br><span style="background-color:rgb(252,252,252);color:rgb(0,0,0);"><strong>In order to operate smoothly, we need a minimum of 4 sets of keys per property. All the sets of keys should be handed to your account manager before the first booking. In case you cannot provide us 4 sets, we will have the possibility to replicate your keys (with extra cost).</strong></span><br><br>So is the following ok?<br><br><span style="background-color:rgb(252,252,252);color:rgb(0,0,0);"><strong>In order to operate smoothly, we need multiple sets of keys per property. Please confirm with your account manager the number of sets required. All sets of keys should be handed to your account manager before the first booking. In case you cannot provide us with the required number of sets, we will be able to assist in getting your keys replicated (with extra cost).</strong></span></p><p>---</p><p>Card description:<br>&nbsp;</p><ul><li>Move the&nbsp;<i>Is it possible to install the lock box?</i>&nbsp;in the&nbsp;<i>Getting in and out&nbsp;</i>section<br>&nbsp;</li><li><i>"we need 4 sets of keys" -&gt; </i>Change for <span style="background-color:rgb(248,248,248);color:rgb(29,28,29);"><i><strong>Pl</strong></i></span><i><strong>ease confirm with your account manager on the number of sets required </strong></i><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);"><i><strong>would be perfect</strong></i></span><br>&nbsp;</li><li><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);">Delete&nbsp;</span><i>are you providing an extra set of keys to guests</i><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);">&nbsp;field</span><br>&nbsp;</li><li>Remove <i>Classic rental price </i><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);">field from the form</span><br>&nbsp;</li><li><span style="background-color:rgb(248,248,248);color:rgb(29,28,29);">Rephrase </span><i>closest metro/tube station for <strong>closest public transport station</strong></i><br>&nbsp;</li><li>Your listing - Add the BookingSync / Airbnb characters limitation for each fields (same of the ones in Rental form)&nbsp;<br>with warnings "Text cannot be longer than XXX characters" for each field.&nbsp;<br>- head<span style="color:hsl(0,0%,0%);">line for this description under 75 characters</span><br><span style="color:hsl(0,0%,0%);">- Summary - less than 150 characters&nbsp;</span><br><span style="color:hsl(0,0%,0%);">- </span><span style="background-color:rgb(255,255,255);color:hsl(0,0%,0%);">10000 characters in total for all the other fields combined&nbsp;</span><br>&nbsp;</li><li><span style="color:hsl(0,0%,0%);">Base price: Add in help text "((Property Manager)) management and channel fees are still to be deducted from the base price."</span><br>&nbsp;</li><li><span style="color:rgb(29,28,29);">Change the landing page once form is submitted by host for "The form has already been submitted to ((Property Manager)) and is currently being reviewed. Please reach out to your account manager should you have any question."</span><br>&nbsp;</li></ul><figure class="image"><img src="https://user-images.githubusercontent.com/18108338/96280008-55610280-0fcf-11eb-8564-e9262a3a6afe.png"></figure>
> @Andrea <span style="background-color:rgb(255,255,255);color:rgb(51,51,51);">"Move the&nbsp;</span><i>Is it possible to install the lock box?</i><span style="background-color:rgb(255,255,255);color:rgb(51,51,51);">&nbsp;in the&nbsp;</span><i>Getting in and out&nbsp;</i><span style="background-color:rgb(255,255,255);color:rgb(51,51,51);">section"</span><br><br>It&#039;s here at the moment, where should it be moved?</p><figure class="image"><img src="https://user-images.githubusercontent.com/18108338/96280051-64e04b80-0fcf-11eb-89e4-1108eebed576.png"></figure>
> @alexandra-ja <span>@<strong id="k-mention">Andrea</strong></span> I have added few changes to this card
