### ISSUE TITLE
[KB 2700] - Available rentals search changes

### ISSUE THREAD

**Issue by acrawford13** [acrawford13/booking-widget#139]
> **Auto-import from Kanbanise**
### Description
<a href="https://www.bnbstaff.net/staffing/available_rentals_search/" target="_blank">https://www.bnbstaff.net/staffing/available_rentals_search/</a>

- Give possibility to order by total price - make sure the ordering is applying remotely&nbsp;

- Add pagination&nbsp;

- Add filters: Premium class, Minimum number of bathrooms

- Allow letters in postcode (ie UK postcode)&nbsp;

<strong>In result display:&nbsp;</strong>
<img src="https://user-images.githubusercontent.com/18108338/96275894-34e27980-0fca-11eb-8c57-df98975dc374.png" style="height:288px; width:1804px" />
- Show total price for the stay for the selected dates instead of price per night

- Add floor / number of rooms / number of beds / number of bathrooms / guest - max number of guessts max number / property size&nbsp;

- Add a copyboard function - when I click on it, I should have information copied as follow:&nbsp;

<strong>Property Name - Full address&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Floor:</strong> 0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <strong>&nbsp; &nbsp; &nbsp; &nbsp;Property surface area:</strong> 27m2&nbsp;
<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Number of room:</strong> 0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <strong>&nbsp; &nbsp; &nbsp;Number of bathrooms: </strong>1,5
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>Number of beds:</strong> 2&nbsp; &nbsp; &nbsp; <strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Maximum number of guests: </strong>2-4
<strong>Total price for the stay</strong> XXX euros.&nbsp;<strong> &nbsp; &nbsp; Listing url:</strong> <a href="http://XXXXX">xxxxxxxxxxxxxxxxxxxxxxxxxxx</a>
- Replace Airbnb listing with direct booking listing (show airbnb only when direct booking is not available)

- Add tooltip for each logo ("Floor: 0", etc )

- Add small warning when Airbnb listing is displayed and tooltip "Direct booking lisiting is not available for this property"

<strong>In result page:</strong>

- Add a clipboard button to copy to clipbaoard all the results (keep the model for individual results)
<img src="https://user-images.githubusercontent.com/18108338/96275897-34e27980-0fca-11eb-9fb7-85e284290b44.png" style="height:932px; width:1838px" />
&nbsp;

### Subtasks
- [x] Give possibility to order by total price - make sure the ordering is applying remotely&nbsp;
- [x] Add filters: Premium class, Minimum number of bathrooms
- [x] Allow letters in postcode (ie UK postcode)&nbsp;
- [x] Show total price for the stay for the selected dates instead of price per night
- [x] Add floor / number of rooms / number of beds / number of bathrooms / guest - max number of guessts max number / property size&nbsp;
- [x] Add a copyboard function
- [x] Add a clipboard button to copy to clipbaoard all the results (keep the model for individual results)
