### ISSUE TITLE
[KB 2945] - Update to the latest stripe api version.

### ISSUE THREAD

**Issue by acrawford13** [acrawford13/booking-widget#143]
> **Auto-import from Kanbanise**
### Description
<a href="https://stripe.com/docs/upgrades#2020-03-02" target="_blank">https://stripe.com/docs/upgrades#2020-03-02</a>

### Subtasks
- [x] Prepare manual tests for the stripe.
- [x] Move stripe.<span style="white-space:pre-wrap">Account.modify_person from </span><span style="white-space:pre-wrap">UploadHostDocuments service to actions. Add manual test for it.</span>
- [x] Move&nbsp;<span style="white-space:pre-wrap">stripe.File.retrieve </span>UploadHostDocuments service to actions
- [x] Move creation link from&nbsp;<span style="white-space:pre-wrap">FetchKycLinkService service to the actions. Add the manual test for it.</span>
- [x] Check all actions are manually tested
- [x] Check all stripe webhooks manualy tested.
- [x] Check all stripe webhooks pass stripe object into next code instead of raw data from event.
- [x] update api to the&nbsp;<a href="https://stripe.com/docs/upgrades#2019-11-05" target="_blank">2019-11-05</a>
- [x] update api to the&nbsp;<a href="https://stripe.com/docs/upgrades#2019-12-03" target="_blank">2019-12-03</a>
- [x] update api to the&nbsp;<a href="https://stripe.com/docs/upgrades#2020-03-02" target="_blank">2020-03-02</a>
- [x] Do the deploy
- [x] update webhook version to the latest 2020-03-02 for Bnblord
- [ ] check webhook version is atest 2020-03-02 for Zeev

----
External link: https://github.com/guestready/bnbstaff/pull/2465
